import Head from "next/head";
import { Inter } from "next/font/google";
import HomePage from "@/components/home/home-page";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  const data = events_categories;
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <HomePage data={data} />
      </>
    </>
  );
}
